### ISSUE TITLE
mac mini 2012 battery error

### ISSUE THREAD

**Issue by silentApplause** [jkuri/macstats#11]
mac mini 2012 late
Catalina 10.15.5

![111111](https://user-images.githubusercontent.com/40753924/86713354-93ee3500-c050-11ea-9df2-283d0d440931.png)
get error on information about battery. But this model acturally  doesn't has battery.

**Comment by jkuri** [comment]
Thanks for report the issue, I fixed this in https://github.com/jkuri/macstats/commit/547c87f276f10deacbd20b608f606e98023ef7e2. Can you please confirm that this works in `macstats@3.1.1`. I just published new version to `npm`.

**Comment by silentApplause** [comment]
The new version works, thanks.
