### ISSUE TITLE
needs XCode to build?

### ISSUE THREAD

**Issue by Offbeatmammal** [jkuri/macstats#3]
tried npm i macstats -g
but get an error during install

> > node-gyp rebuild
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

no big drama, installing XCode now, but might be good to call out as a prerequisite?

**Comment by jkuri** [comment]
I believe you only need xcode command line tools, if its even possible to install only those.

**Comment by Offbeatmammal** [comment]
I think I have those, installing the full XCode package now and will update if that works (not really a big deal, just a slow download!)

**Comment by jkuri** [comment]
okay, thanks.

**Comment by Offbeatmammal** [comment]
looks like it needed the full thing, fine after installing and agreeing to the license

**Comment by jkuri** [comment]
okay, thank you for this info.
