### ISSUE TITLE
battery.temparature API typo

### ISSUE THREAD

**Issue by awaxa** [jkuri/macstats#4]
https://github.com/jkuri/macstats/search?q=temparature

I would have submitted a quick pull request yesterday instead but I'm not sure how best to prevent breaking the API for any existing users.

**Comment by jkuri** [comment]
hi @awaxa. didn't even noticed that since now. please make a PR and I will accept it right away.

**Comment by 0xflotus** [comment]
This is done.

**Comment by jkuri** [comment]
thanks
