### ISSUE TITLE
Battery temperature rounds to the next integer

### ISSUE THREAD

**Issue by charleschenster** [jkuri/macstats#8]
If I run`ioreg -rn AppleSmartBattery` locally on my computer I see that battery temperature is returned as `3075`. However, here https://github.com/jkuri/macstats/blob/master/src/battery.ts#L105 `toFixed(0)` is called to round the number. Are you open to preserving the precision here and removing `toFixed(0)`?

**Comment by charleschenster** [comment]
@jkuri ping on this. i'm happy to open up a PR

**Comment by jkuri** [comment]
hi @charleschenster sorry for super late response :) please open a PR. I just updated library to work with Node versions newer than 8.
